# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Movies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies
  pod 'RxSwift', '4.0'
  pod 'RxCocoa', '4.0'
  pod 'RxDataSources', '3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = 4.0
    end
  end
end
